spring:
   profiles:
      active:
      - dev

---
spring:
   profiles: dev
   application:
      name:microservice-test-dev-001
      
---
spring:
   profiles: default
   application:
      name: microservice-test-default
