spring:
  profiles:
    active:
    - dev
---    
server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://admin:a@eureka1:1001/eureka
  instance:
    prefer-ip-address: true
    instance-id: base-microservice-hystrix-turbine-00001002

turbine:
  app-config: piclib-web #  配置Eureka中的serviceId列表，表明监控哪些服务, 启动后从配置中心中进行更新
  aggregator:
    cluster-config: default     #  指定聚合哪些集群，多个使用","分割，默认为default。
  cluster-name-expression: new String("default")   #表示集群的名字为default
  combine-host-port: true   
  
spring:
  profiles: dev
#   security:
#     user:
#       name: admin
#       password: a
  
