server:
  port: 9501

eureka:
  client: # zuul客户端到Eureka注册, 这样 feign的客户端就能找到zuul服务了
    service-url:
      defaultZone: http://admin:a@eureka1:7301/eureka
    register-with-eureka: true      #暂时不注册
  instance:
   instance-id: base-microservice-zuul-gateway   #实例名
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2    #设置心跳间隔时间
    lease-expiration-duration-in-seconds: 5  # 租约超时时间间隔

spring:
  profiles: dev
  application:
    name:  base-microservice-zuul-gateway    # zuul网关服务在eureka中的服务名
  security:   # zuul网关服务的用户认证
    user:
      name: admin
      password: a
# zuul:
#   #routes:    #路由配置
#    # microservice-provider-user:  /user-proxy/**
#   routes:
#     #user.path: /user-proxy/**
#     #user.serviceId: microservice-provider-user
#     user1:
#       path: /user1-proxy/**
#       serviceId: microservice-provider-user
#     user2: #传统的路由方式
#       path: /user2-proxy/**
#       url: http://localhost:5555/
#     product:
#       path: /product-proxy/**
#       serviceId: microservice-provider
#       sensitiveHeaders:
#   ignored-services:
#     "*"
#   prefix: /yc-api    #公共前缀

zuul:
  routes:
    piclib:
      path: /piclib-proxy/**
      serviceId: MICROSERVICE-PROVIDER-PICLIB
      sensitiveHeaders:
  ignored-services:      # "*"代表隐藏所有的服务名，这样就不能通过zuul直接用服务名访问真实的服务了.
    "*"
  prefix: /yc-api    #公共前缀
  sensitiveHeaders:    #去掉敏感头设置,   以实现将  权限 信息向过滤器链传递 的目标



logging:
