server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://admin:a@eureka1:1001/eureka
  instance:
    prefer-ip-address: true
    instance-id: base-microservice-hystrix-turbine

turbine:
  app-config: base-microservice-provider  #需要收集信息的服务名
  cluster-name-expression: new String("default")
  combine-host-port: true # 同一主机上的服务通过主机名和端口号的组合来进行区分，默认以host来区分
  
spring:
  profiles: dev
#   security:
#     user:
#       name: admin
#       password: a
  
