server:
  port: 9501

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:a@eureka1:1001/eureka
    register-with-eureka: true      #暂时不注册
  instance:
    instance-id: base-microservice-zuul-gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2    #设置心跳间隔时间
    lease-expiration-duration-in-seconds: 5  # 租约超时时间间隔

spring:
  profiles: dev
  application:
    name: base-microservice-zuul-gateway
  security:
    user:
      name: admin
      password: a
zuul:
  #routes:    #路由配置
   # microservice-provider-user:  /user-proxy/**
  routes:
    #user.path: /user-proxy/**
    #user.serviceId: microservice-provider-user
    user1:
      path: /user1-proxy/**
      serviceId: microservice-provider-user
    user2: #传统的路由方式
      path: /user2-proxy/**
      url: http://localhost:5555/
    product:
      path: /product-proxy/**
      serviceId: microservice-provider
      sensitiveHeaders:
  ignored-services:
    "*"
  prefix: /yc-api    #公共前缀
